create table public.employee_permissions (
  id uuid not null default gen_random_uuid (),
  employee_id uuid null,
  can_manage_courses boolean null default false,
  can_manage_programs boolean null default false,
  can_manage_enrollments boolean null default false,
  can_manage_students boolean null default false,
  can_manage_content boolean null default false,
  can_manage_payments boolean null default false,
  can_manage_leads boolean null default false,
  can_manage_employees boolean null default false,
  can_manage_placements boolean null default false,
  can_manage_schedule boolean null default false,
  can_manage_testimonials boolean null default false,
  can_manage_coupons boolean null default false,
  can_manage_notifications boolean null default false,
  can_manage_video_security boolean null default false,
  can_manage_certificates boolean null default false,
  constraint employee_permissions_pkey primary key (id),
  constraint employee_permissions_employee_id_key unique (employee_id),
  constraint employee_permissions_employee_id_fkey foreign KEY (employee_id) references employees (id) on delete CASCADE
) TABLESPACE pg_default;