export { Skeleton } from "@/components/ui/skeleton"

export { CardSkeleton, StatCardSkeleton } from "./CardSkeleton"
export { HeroSkeleton } from "./HeroSkeleton"
export { CourseCardSkeleton, CourseGridSkeleton } from "./CourseCardSkeleton"
export { ProgramCardSkeleton, ProgramGridSkeleton } from "./ProgramCardSkeleton"
export { VideoSkeleton, VideoPlayerSkeleton } from "./VideoSkeleton"
export { TableSkeleton } from "./TableSkeleton"
export { FormSkeleton, FormFieldSkeleton } from "./FormSkeleton"
export { ProfileSkeleton } from "./ProfileSkeleton"
export { SidebarSkeleton, LessonSidebarSkeleton } from "./SidebarSkeleton"
export { NavbarSkeleton } from "./NavbarSkeleton"
export { FooterSkeleton } from "./FooterSkeleton"
export { AdminDashboardSkeleton, StudentDashboardSkeleton } from "./DashboardSkeleton"
export { LessonContentSkeleton } from "./LessonSkeleton"
export { ChartSkeleton } from "./ChartSkeleton"
export { BlogCardSkeleton, BlogGridSkeleton } from "./BlogCardSkeleton"
export { TestimonialCardSkeleton } from "./TestimonialCardSkeleton"
export { PageHeaderSkeleton, SectionHeaderSkeleton } from "./PageHeaderSkeleton"
